version: '3.4'

services:
  mongo:
    build: ./mongo
    container_name: mongo
    volumes:
      - mongo-data:/data/db
  postgres:
    build: ./postgres
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret123
  presto:
    build: ./presto
    container_name: presto
    ports:
      - "8080:8080"
  metabase:
    image: metabase/metabase:v0.33.4
    container_name: metabase
    volumes:
      - ./data/metabase:/metabase-data
    ports:
      - "8000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db

  
volumes:
  mongo-data:
    name: mongo-data
  postgres-data:
    name: postgres-data
